# Settings → Privacy & Security → For developers → Developer Mode → ✔️On

# The following line is untested, and has been generated by Copilot on a MacBook.
Set-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\AppModelUnlock" `
                 -Name "AllowDevelopmentWithoutDevLicense" `
                 -Value 1 -Type DWord