" A simple yet powerful .vimrc file.
"
" Maintainer:       Daniel Orbach <ddorbach@gmail.com>
" Last Change:      2025 Feb 15
" Operating System: macOS
"
" This file is composed of $VIMRUNTIME/vimrc_example.vim and mimics the default
" settings of Vim on Windows (git-for-windows). I've modified it to suit my
" needs and preferences. It is a good starting point for anyone who wants to
" use Vim for programming on macOS.
"
" To use it, copy it to ~/.vimrc.

" When started as "evim", evim.vim will already have done these settings, bail
" out. Though, Easy Vim is not commonly used on macOS.
if v:progname =~? "evim"
  finish
endif

" Setting some decent VIM settings for programming
" This source file comes from git-for-windows build-extra repository (git-extra/vimrc)

unlet g:skip_defaults_vim       " Unset the flag to skip defaults.vim (set by macOS /usr/share/vim/vimrc)
ru! defaults.vim                " Use Enhanced Vim defaults
set mouse=                      " Reset the mouse setting from defaults
aug vimStartup | au! | aug END  " Revert last positioned jump, as it is defined below
let g:skip_defaults_vim = 1     " Do not source defaults.vim again (after loading this system vimrc)

set ai                          " set auto-indenting on for programming
set showmatch                   " automatically show matching brackets. works like it does in bbedit.
set vb                          " turn on the "visual bell" - which is much quieter than the "audio blink"
set laststatus=2                " make the last line where the status is two lines deep so you can see status always
set showmode                    " show the current mode
set clipboard=unnamed           " set clipboard to unnamed to access the system clipboard under windows
set wildmode=list:longest,longest:full   " Better command line completion

" Show EOL type and last modified timestamp, right after the filename
" Set the statusline
set statusline=%f               " filename relative to current $PWD
set statusline+=%h              " help file flag
set statusline+=%m              " modified flag
set statusline+=%r              " readonly flag
set statusline+=\ [%{&ff}]      " Fileformat [unix]/[dos] etc...
set statusline+=\ (%{strftime(\"%H:%M\ %d/%m/%Y\",getftime(expand(\"%:p\")))})  " last modified timestamp
set statusline+=%=              " Rest: right align
set statusline+=%l,%c%V         " Position in buffer: linenumber, column, virtual column
set statusline+=\ %P            " Position in buffer: Percentage

" Some terminal emulators support 256 colors, but not true colors. This is the
" case for Apple Terminal and iTerm2. When true colors are supported, we can
" enable them by setting the termguicolors option.
if &term !~ '256color'
    set termguicolors
endif

"------------------------------------------------------------------------------
" Only do this part when compiled with support for autocommands.
if has("autocmd")
    " Set UTF-8 as the default encoding for commit messages
    autocmd BufReadPre COMMIT_EDITMSG,MERGE_MSG,git-rebase-todo setlocal fileencoding=utf-8

    " Remember the positions in files with some git-specific exceptions"
    autocmd BufReadPost *
      \ if line("'\"") > 0 && line("'\"") <= line("$")
      \           && &filetype !~# 'commit\|gitrebase'
      \           && expand("%") !~ "ADD_EDIT.patch"
      \           && expand("%") !~ "addp-hunk-edit.diff" |
      \   exe "normal! g`\"" |
      \ endif

      autocmd BufNewFile,BufRead *.patch set filetype=diff

      autocmd Filetype diff
      \ highlight WhiteSpaceEOL ctermbg=red |
      \ match WhiteSpaceEOL /\(^+.*\)\@<=\s\+$/
endif " has("autocmd")

" Backups behave according to the following settings (see :help backup) :
"
" 'backup' 'writebackup'  action
"    off       off        no backup made
"    off       on         backup current file, deleted afterwards (default)
"    on        off        delete old backup, backup current file
"    on        on         delete old backup, backup current file
"
" We want to keep as much history as possible, without cluttering the working
" directory with backup files. So we set backups and undos to be stored in a
" separate directory.
set backup      " keep a backup file (without restore to previous version)
set backupdir=~/.vim/backup//   " keep backup files in a separate directory
if has('persistent_undo')
  set undofile  " keep an undo file (undo changes after closing)
  set undodir=~/.vim/undo//     " keep undo files in a separate directory
endif

if &t_Co > 2 || has("gui_running")
  " Switch on highlighting the last used search pattern.
  set hlsearch
endif

" Put these in an autocmd group, so that we can delete them easily.
augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78
augroup END

" Add optional packages.
"
" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
" The ! means the package won't be loaded right away but when plugins are
" loaded during initialization.
if has('syntax') && has('eval')
  packadd! matchit
endif
