#!/bin/zsh

# TODO: if interactive shell, open 'gh auth login' and let the user interact with the CLI

# TODO: configure SSH code signing with 1Password

# TODO: configure gh CLI
gh extension install github/gh-copilot