#!/bin/zsh
#
# This script creates symlinks under the user's HOME directory pointing to
# the dotfiles in this repository.
#
# All the dotfiles are located under the macos/ directory of this repository.

setopt errexit nounset pipefail  # Enable strict mode for better error handling



# === HELPERS ===

# Print message in green.
info() {
  echo -e "\\033[1;32m[INFO]\\033[0m  $*"
}

# Print message in yellow.
warn() {
  echo -e "\\033[1;33m[WARN]\\033[0m  $*"
}

# Print message in red, and exit with non-zero code.
error() {
  echo -e "\\033[1;31m[ERROR]\\033[0m $*" >&2
  exit 1
}

# Function to create a symlink.
create_symlink() {
  local source_file="$1"
  local target_file="$2"

  if [[ -L "$target_file" ]]; then
    # Check if the symlink points to the correct source.
    if [[ "$(readlink "$target_file")" == "$source_file" ]]; then
      info "✅ Symlink already exists: $target_file -> $source_file"
    else
      warn "⚠️  Symlink conflict: $target_file -> $(readlink "$target_file") (expected $source_file)"
    fi
  elif [[ -e "$target_file" ]]; then
    # File exists but is not a symlink.
    error "‼️  File conflict: $target_file already exists and is not a symlink."
  else
    # Create the symlink.
    ln -s "$source_file" "$target_file"
    info "🔗 Created symlink: $target_file -> $source_file"
  fi
}



# === MAIN ===

BOOTSTRAPD_DIR="$(dirname "$(realpath "$0")")"  # The macos/bootstrap.d/ folder.
DOTFILES_DIR="$(dirname "$BOOTSTRAPD_DIR")"  # The macos/ folder.
DOTFILES=(
  "zshenv"
  "zprofile"
  "zshrc"
)

info "Starting dotfiles symlink to $DOTFILES_DIR..."

# Iterate over dotfiles in the macos dotfiles directory.
for file in "${DOTFILES[@]}"; do
    TARGET="$DOTFILES_DIR/$file"
    LINK="$HOME/.$file"
    create_symlink "$TARGET" "$LINK"
done

info "Dotfiles symlink process complete."
