#!/bin/zsh
#
# This init script installs the latest Homebrew on a macos machine.
#
# This script is safe to execute multiple times on the same machine (idempotent).
#
# Terminology: <https://docs.brew.sh/Formula-Cookbook#homebrew-terminology>

# Enable strict mode for better error handling.
setopt ERREXIT NOUNSET PIPEFAIL


command_exists() {
  command -v "$@" >/dev/null 2>&1
}

# Install Homebrew if not already installed.
if command_exists brew ; then
    echo "Homebrew already installed."
    exit 0
else
    echo "Installing Homebrew..."
fi

# The following command is recommended by <https://brew.sh> to install brew.
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# The command above only modifies files under /opt/homebrew (on Apple Silicon).
# For this reason, the installation does not automatically modify the PATH
# variable. For this reason, the installation script instructs the user to
# manually configure the current shell (Zsh in this case) approritately.
if ! grep -q '# DOTFILES: Homebrew' ~/.zprofile; then
  cat >> ~/.zprofile <<EOF
# DOTFILES: Homebrew
eval "\$(/opt/homebrew/bin/brew shellenv)"
EOF
  echo "~/.zprofile updated to evaluate Homebrew environment."
else
  echo "~/.zprofile already evaluates Homebrew environment."
fi
