# Dotfiles Installation (macOS)
#
# This workflow automates the installation and setup of dotfiles on macOS environments.
# It handles the complete process from cleaning up existing software to verifying the
# installation and running tests.
#
# Currently, this workflow is designed to run on Apple Silicon only. As new operating
# systems are released, the matrix strategy can be updated manually to include additional
# versions.
#
# The workflow can be triggered by pushing changes to main, creating pull requests, or
# manually through workflow dispatch.
name: macos dotfiles

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-15  # The latest macOS running on Apple Silicon.

    defaults:
      run:
        # Using zsh as the default shell instead of bash.
        #
        # Using -l (login) ensures that the shell starts as a login shell, which is
        # important for loading the correct environment variables and configurations.
        #
        # Spec: <https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#defaultsrunshell>
        shell: /bin/zsh -l {0}

    steps:
      - name: Clean up pre-installed software
        run: |
          brew uninstall --cask --force $(brew list --cask)
          brew uninstall --formula --ignore-dependencies --force $(brew list --formula)
          # brew uninstall --cask --force firefox google-chrome
          brew cleanup --prune-prefix
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"

      - uses: actions/checkout@v4

      - name: Bootstrap
        run: ./macos/bootstrap

      - name: Check (zsh)
        run: ./macos/check

      - name: 👁️ Inspect ~/.zshrc
        run: cat ~/.zshrc

      - name: 👁️ Inspect ~/.zshenv
        run: cat ~/.zshenv

      - name: 👁️ Inspect ~/.zprofile
        run: cat ~/.zprofile
